### PR TITLE
Bug fix for issue #43

### LINKED ISSUE #43: Intake motor stutters
The intake roller motor has been stuttering when in operation.  It appears that this is due to turning off the motor in the subsystem's `periodic()` method: https://github.com/AGHSEagleRobotics/frc1388-2024/blob/d8b678322ebaeeda120680cbaf7de17bec0543c7/frc1388-2024/src/main/java/frc/robot/subsystems/IntakeSubsystem.java#L103

It's bad to set a motor power/speed in more than one place at the same point in time.  In this case, the `setRollerMotor()` method is setting the desired power level, but `periodic()` is setting it back to zero.  This conflict causes erratic motor power levels.  In this case, the motor was bouncing between high power and zero power, which was the likely cause of motor stuttering.  When the motor power fluctuates rapidly, it causes the motor to heat up.  The motor in question smoked and can no longer be considered to be reliable.

Lessons to be learned:
- Be **VERY** careful when setting motor power, to ensure that you're not setting the power in more than one place at the same time.
- If you add temporary code for debugging, be **VERY** sure you remove that code before committing.  This is one of the main reasons why I _strongly_ recommend always reviewing your changes before committing.

### PR DESCRIPTION
**Pull request by jtechau**
Removed a call to continuously turn off the motor in the intake subsystem's periodic().

Fixes #43

### CODE REVIEW

File: frc1388-2024/src/main/java/frc/robot/subsystems/IntakeSubsystem.java [hunk 1]
```diff
@@ -100,6 +100,8 @@ public void periodic() {
     SmartDashboard.putBoolean("upper limit", getUpperLimit());
     SmartDashboard.putBoolean("lower limit", getLowerLimit());
     SmartDashboard.putBoolean("beam break", getBeamBreak());
-    m_rollerMotor.set(0.0);
+
+//    m_rollerMotor.set(0.0);
```
Comment (calvinxp) [inline frc1388-2024/src/main/java/frc/robot/subsystems/IntakeSubsystem.java]: Remove this line

**Review by calvinxp — CHANGES_REQUESTED** [review]
